### ISSUE TITLE
Crashing on server startup

### ISSUE THREAD

**Issue by f1den** [BlakeBr0/Cucumber#34]
2023-12-12 18:21:55,473 INFO  [main] Extended Crafting.loadSingularities(67): Loaded 19 singularity type(s) in 6 ms
2023-12-12 18:21:55,475 WARN  [main] n.m.s.Main.main(214): Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.6 of loader 'MC-BOOTSTRAP' @58ce9668; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @58ce9668)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:212) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.3.5.jar%23124!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2369!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at com.mohistmc.MohistMCStart.main(MohistMCStart.java:93) [mohist-1.19.2-82-server.jar:1.19.2-82]
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.6 of loader 'MC-BOOTSTRAP' @58ce9668; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @58ce9668)
	at com.blakebr0.cucumber.helper.RecipeHelper.fireRecipeManagerLoadedEvent(RecipeHelper.java:74) ~[common.lib.Cucumber-1.19.2-6.0.10.jar%23165!/:6.0.10]
	at net.minecraft.world.item.crafting.RecipeManager.handler$zzh000$cucumber$apply(RecipeManager.java:542) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:65) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:37) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.Util.m_214652_(Util.java:781) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.Util.m_214679_(Util.java:770) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	at net.minecraft.server.Main.main(Main.java:187) ~[server-1.19.2-20220805.130853-srg.jar%23196!/:?]
	... 14 more

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Server: Mohist (latest)
 - Cucumber: 6.0.10
 
 Client starts normal, but server crashes

**Comment by BlakeBr0** [comment]
Are you using a custom server? This looks like a similar error to https://github.com/BlakeBr0/ExtendedCrafting/issues/182

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
