### ISSUE TITLE
A Crash on server startup

### ISSUE THREAD

**Issue by YusJade** [BlakeBr0/Cucumber#37]
[10:25:46 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @58326051; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @58326051)
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at net.minecraft.server.Main.main(Main.java:250) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%23185!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23100!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:107) [mohist-1.20.1-595-server.jar:1.20.1-629]
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap cannot be cast to class com.google.common.collect.ImmutableMap$Builder (it.unimi.dsi.fastutil.objects.Object2ObjectLinkedOpenHashMap is in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @58326051; com.google.common.collect.ImmutableMap$Builder is in module com.google.common@31.1-jre of loader 'MC-BOOTSTRAP' @58326051)
        at com.blakebr0.cucumber.helper.RecipeHelper.fireRecipeManagerLoadedEvent(RecipeHelper.java:74) ~[Cucumber-1.20.1-7.0.8.jar%23553!/:7.0.8]
        at net.minecraft.world.item.crafting.RecipeManager.handler$ceh000$cucumber$apply(RecipeManager.java:4542) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:66) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:37) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        at net.minecraft.server.Main.main(Main.java:220) ~[server-1.20.1-20230612.114412-srg.jar%23858!/:?]
        ... 16 more

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 Minecraft: 1.20.1
Server: Mohist (latest)
Cucumber: 7.0.8

I can\`t find `extendedcrafting-common.toml` in `server/config`, how can I fix this？

**Comment by BlakeBr0** [comment]
That file should be wherever your config files are. I think Iron Jetpacks also can cause this issue, which would require you to go into the config for that mod and disable all of the options in the dynamic recipe section. This would mean that all of the jetpacks won't have recipes and they would all need to be added manually.
